#Makefile 

#target: list of dependencies
#<literal tab> command to build target from dependencies
#all: names of all things to build ex: tour fib hello
#clean: deletes the exe files
	#rm hello fib time_table *~ core

tour: tour.c
	gcc tour.c -o tour
clean:
	rm -f tour *~ core
